name: nachsorgecompass
description: "App für Vor- und Nachsorgeengel mit Terminanfrage-Funktionalität"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  validators: ^3.0.0
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/.env

# 🔽 Flutter Native Splash Konfiguration
flutter_native_splash:
  color: "#F5F5F5"
  image: assets/images/splash.png
